### ISSUE TITLE
YAML aliases aren’t merged properly

### ISSUE THREAD

**Issue by natesilva** [tuxtina/json2yaml#6]
This example is [from Bitbucket](https://confluence.atlassian.com/bitbucket/yaml-anchors-960154027.html). I stripped it down to make the problem easier to see.

Notice that if you convert this to JSON, the final `step` is not properly converted.

```yaml
definitions: 
  steps:
    - step: &deploy
        name: Deploy
        deployment: test

master:
  - step:
      <<: *deploy
      deployment: production
```

**Expected result**: It should convert to this:

```json
{
  "definitions": {
    "steps": [
      {
        "step": {
          "name": "Deploy",
          "deployment": "test"
        }
      }
    ]
  },
  "master": [
    {
      "step": {
        "name": "Deploy",
        "deployment": "production"
      }
    }
  ]
}
```

**Actual result**: It is converted to this:

```json
{
  "definitions": {
    "steps": [
      {
        "step": {
          "name": "Deploy",
          "deployment": "test"
        }
      }
    ]
  },
  "master": [
    {
      "step": {
        "<<": {
          "name": "Deploy",
          "deployment": "test"
        },
        "deployment": "production"
      }
    }
  ]
}
```

The problem is near the end, where you see `"<<": {`. The parser must be having a hard time with the merge syntax (`<<:`).
